apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: scanning-operator
  name: openshift-scanning-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanning-operator
  namespace: openshift-scanning-operator
  labels:
    control-plane: scanning-operator
spec:
  selector:
    matchLabels:
      control-plane: scanning-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: scanning-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: quay.io/dedgar/scanning-operator:v0.0.21
        imagePullPolicy: Always
        name: scanning-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "scanning-operator"
      terminationGracePeriodSeconds: 10
