
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: scanning-operator-role
  namespace: openshift-scanning-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - managed.openshift.io
  resources:
  - loggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - loggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed.openshift.io
  resources:
  - loggerservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - loggerservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed.openshift.io
  resources:
  - scanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - scanners/status
  verbs:
  - get
  - patch
  - update
